### ISSUE TITLE
AP1.1 Erstellung und Überarbeitung des Proposals

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#1]
### Beschreibung
Das Proposal hilft dabei die Bachelorarbeit zu planen.

### Akzeptanzkriterien
* Die Überarbeitung des Proposals gilt als erledigt,
wenn die Betreuenden keine weiteren Einwände mehr haben.  

### Tasks
- [x] Feedback der anderen nutzen und mit einbringen
- [x] Ziele klarer definieren #24
- [x] Eine Entscheidung treffen. Soll der Schwerpunkt auf der Analyse oder Visualisierung liegen? #25
- [x] Wie wird am Ende das Ergebnis gemessen? #23 
- [x] Das überarbeitete Proposal den Betreuenden zukommen lassen #26
- [x] Es gab ein Feedback zu dem Proposal 
- [x] ggf. Nachbesserungen
- [x] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen
