### ISSUE TITLE
AP1.2 Festlegung des Bachelorarbeitstitels

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#2]
### Beschreibung
Der Bachelorarbeitstitel muss zu der Anmeldung der Bachelorarbeit feststehen.

### Akzeptanzkriterien
* Der Bachelorarbeitstitel gilt als festgelegt, wenn die Betreuenden keine weiteren Einwände mehr haben.  

### Einschränkungen
* Der Bachelorarbeitstitel sollte nicht zu kurz, aber auch nicht zu lang sein.

### Tasks
- [x] Änderung des Bachelorarbeitstitels
- [x] Absprache mit den Betreuenden
- [x] Ein Bachelorarbeitstitel wurde festgelegt
- [x] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen

**Comment by JudithBre** [comment]
Is finished
