### ISSUE TITLE
AP2.1 Gliederung festlegen

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#29]
### Beschreibung
Eine erste grobe Gliederung wird im Bachelorarbeitsvorbereitungskurs vorgeschlagen. Diese wird weiter ausgearbeitet.

### Akzeptanzkriterien
* Die Gliederung gilt als erledigt, wenn die Betreuenden keine weiteren Einwände mehr haben.    

### Tasks
- [x] Gliederung aus dem Bachelorarbeitsvorbereitungskurs herausschreiben (https://github.com/JudithBre/Organisation-der-BA/issues/27)
- [x] Gliederung weiter ergänzen
- [x] Die erste Gliederung den Betreuenden vorschlagen
- [x] Die Gliederung wird ggf. überarbeitet
- [x] Die Gliederungspunkte werde als Kategorien in Citavi eingepflegt
- [x] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen

## benötigtes Wissen: 
- Was zählt als Anhang? Was zählt als Text?
- Wie viele Seiten Text pro Kapitel?
