### ISSUE TITLE
AP2.2 Grundstruktur in LaTeX umsetzen

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#30]
### Beschreibung
Das Dokument in LaTeX kann aus beliebig vielen Dateien bestehen. Jedes Kapitel der Bachleorarbeit erhält seine eigene LaTeX Datei. Zu Beginn des Dokuments werden die Formatvorgaben einmal festgelegt und sind veränderbar.

### Akzeptanzkriterien
* Die Grundstruktur in LaTeX gilt als erledigt, wenn die erste grobe Gliederung in dem LaTeX Projekt vorhanden ist und die Betreuenden keine weiteren Einwände mehr haben.    

### Tasks
- [x] Anlegen eines LaTeX Projektes
- [x] Die Grundstruktur aus #29 in LaTeX übertragen
- [x] Die erste grobe Gliederung in dem LaTeX Projekt ist vorhanden
- [x] Die erste grobe Gliederung in LaTeX geht ins Review
- [x] ggf. Nachbesserungen
- [x] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen

## benötigtes Wissen: 
* Die erste grobe Gliederung sollte bereits festgelegt sein.
