### ISSUE TITLE
AP2.3 einheitliches Vorgehen bei jedem zu verfassenden Kapitel in der Bachelorarbeit genauer erarbeiten

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#31]
### Beschreibung
Die Erstellung einer Bachelorarbeit wird zunächst konzeptionell angegangen, bevor es in die konkrete Umsetzung geht. Dabei wird ein einheitliches Vorgehen für das Verfassen der einzelnen Kapitel angestrebt.

### Akzeptanzkriterien
* Die Erarbeitung gilt als erledigt, wenn die Betreuenden keine weiteren Einwände mehr haben und die Studierende weiß was zu tun ist.  

### Tasks
- [ ] den Text vorbereiten - recherchieren und exzerpieren
- [ ] das Material ordnen - strukturieren
- [ ] den Text planen - argumentieren und gliedern
- [ ] den Text erarbeiten - schreiben und formulieren
- [ ] den Text überarbeiten - editieren
- [ ] den Text fertigstellen - korrigieren

## benötigtes Wissen: 
* Das benötigte Wissen eignet sich die Studierende selbst an.
