### ISSUE TITLE
AP1.4 Zitierweise festlegen

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#4]
### Beschreibung
Mithilfe von Zitaten werde die eigenen Aussagen belegt. Die Ausarbeitung wird nachvollziehbar und überprüfbar.

### Akzeptanzkriterien
* Die Zitierweise gilt als festgelegt, wenn die Betreuenden und die Studierende sich auf eine geeignete Zitierweise einigen konnten. 

### Einschränkungen
Keine, da es keine Empfehlungen für eine Zitierweise in wissenschaftlichen Arbeiten vom Institut für Geoinformatik gibt.

### Tasks
- [x] Zitierweisen recherchieren #16
- [x] Zitierweisen abwägen #15
- [x] Einen Vorschlag für eine mögliche Zitierweise in der Bachelorarbeit den Betreuenden vorschlagen. #14
- [x] Untersuchung der BA auf Plagiate mit bedenken #14
- [ ] Die Betreuenden und die Studierende konnten sich auf eine geeignete Zitierweise einigen
- [ ] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen

**Comment by JudithBre** [comment]
Die Wünsche der Betreunden wurden berücksichtigt.
