### ISSUE TITLE
AP1.5 Organisation der Bachelorarbeit

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#5]
### Beschreibung
Die Organisation des Arbeitsprozesses unterstützt die Zielerreichung bei der Bachelorarbeit. 

### Akzeptanzkriterien
* Die vorbereitende Organisation der Bachelorarbeit gilt als erledigt, wenn die Studierenden der Meinung ist, dass die Organisation abgeschlossen ist.  

### Tasks
- [x]  Kanban Board in Trello anlegen
- [x] Das Scrum-Framework wird verwendet/angewendet #12 
- [x] Ein Logbuch wird verwendet/angewendet #13 
- [x] Ein Citavi Projekt für die Bachelorarbeit anlegen #17
- [x] Verwerfen des Kanban Boards in Trello. JudithBre/Organisation-der-BA#8
- [x] Anlegen eines GitHub Repositories

**Comment by JudithBre** [comment]
alle Tasks sind abgeschlossen und damit auch mein allererstes Arbeitspaket!!! :) 💯 💛
