### ISSUE TITLE
AP1.6 Zeitplanung für die Bachelorarbeit

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#6]
### Beschreibung
Eine Zeitplanung verschafft der Studierenden und den Betreuenden einen guten Überblick über die auszuführenden Tätigkeiten während der Zeit bis zur Abgabe der Bachelorarbeit. 
Die Zeit kann möglichst effektiv eingeteilt werden und die Studierende zwingt sich damit selbst dazu das gesamte Projekt mit allen Einzelheiten zu durchdenken.

### Akzeptanzkriterien
* Die erste Zeitplanung gilt als erledigt, wenn die Betreuenden keine weiteren Einwände mehr haben.  

### Einschränkungen
*  Die Zeitplanung ist so zu begrenzen, dass die 12 Wochen Bearbeitungszeit eingehalten werden kann.

### Risiken
* Keine Vorhersehbarkeit. Daher ist das Projektcontrolling von enormer Wichtigkeit.

### Tasks
- [x] Anfertigung von einem Projektstrukturplan (PSP). JudithBre/Organisation-der-BA#9
- [x] Mithilfe des PSP wird ein Gantt-Diagramm in dem Programm GanttProject erstellt. Inklusive Abhängigkeiten von Aktivitäten und Meilensteinen. #10 
- [x] Einrichten eines Projektcontrollings über die gesamte Zeit der Bachelorarbeit hinweg. #11 
- [x] Der erste Zeitplan geht an die Betreuenden zum Review
- [x] ggf. nachbessern, falls Einwände bestehen
- [x] Die Betreuenden haben keine weiteren Einwände mehr
- [x] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen

**Comment by JudithBre** [comment]
- [ ] Die erste Zeitplan geht an die Betreuenden zum Review
- [ ] ggf. nachbessern, falls Einwände bestehen
- [ ] die Betreuenden haben keine weiteren Einwände mehr, damit gilt das Arbeitspaket als erledigt

Die Tasks wurden ergänzt.
### Akzeptanzkriterien
* Die erste Zeitplanung gilt als erledigt, wenn die Betreuenden keine weiteren Einwände mehr haben!
