### ISSUE TITLE
AP1.7 Anmeldung der Bachelorarbeit

### ISSUE THREAD

**Issue by JudithBre** [JudithBre/Organisation-der-BA#7]
### Beschreibung
Damit mit der Arbeit an der Bachelorarbeit begonnen werden kann, ist dessen Anmeldung notwendig.

### Akzeptanzkriterien
* Das Issue zur Anmeldung der Bachelorarbeit ist erledigt, wenn eine entsprechende Rückmeldung eingegangen ist

### Tasks
- [x] Wo muss die Bachelorarbeit angemeldet werden? #18 
- [x] Von wem wird die Bachelorarbeit angemeldet? #19 
- [x] Sind weitere Informationen/Angaben notwendig? #20 
- [x] Die Anmeldung der Bachelorarbeit ist erfolgt #28 
- [x] Eine Rückmeldung ist eingegangen, dass die Bachelorarbeit als angemeldet gilt #28 
- [x] Die Aktzeptanzkriterien sind erfüllt und das Issue wird geschlossen

**Comment by JudithBre** [comment]
Is finished
